---
# Remove controller containers.

- name: remove controller
  docker_container:
    name: controller
    image: "{{ docker_registry }}{{ docker_image_prefix }}/controller:{{ docker_image_tag }}"
    state: absent
  ignore_errors: True

- name: remove controller log directory
  file:
    path: "{{ whisk_logs_dir }}/controller"
    state: absent
  become: true