apiVersion: v1
kind: Service
metadata:
  labels:
    name: apigateway
  name: apigateway
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 8080 
      name: mgmt
  selector:
    app: apigateway
    stage: dev
