apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: redis-master-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        stage: dev
    spec:
      containers:
      - name: redis
        image: redis:3.2
        ports:
        - containerPort: 6379
      restartPolicy: Always

