---

# Download the cli to openwhisk_home

- name: "download cli (linux) to openwhisk home at {{ openwhisk_home }}"
  local_action: >
    get_url
    url="https://{{ groups['edge'] | first }}/cli/go/download/linux/amd64/wsk"
    dest="{{ openwhisk_home }}/bin/wsk"
    mode=0755
    validate_certs=False
  when: "'environments/mac' not in inventory_dir"

- name: "download cli (mac) to openwhisk home at {{ openwhisk_home }}"
  local_action: >
    get_url
    url="https://{{ groups['edge'] | first }}/cli/go/download/mac/amd64/wsk"
    dest="{{ openwhisk_home }}/bin/wsk"
    mode=0755
    validate_certs=False
  when: "'environments/mac' in inventory_dir"
