apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-couchdb-master-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-1
