apiVersion: v1
kind: Service
metadata:
  labels:
    name: controller
  name: controller
spec:
  type: NodePort
  ports:
  - port: 10001
    targetPort: 8080
  selector:
    app: controller
    stage: dev
