apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx 
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 8443
    targetPort: 8443
    name: adminportal
  selector:
    app: nginx
    stage: dev
