apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
        stage: dev
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.4
        ports:
        - containerPort: 2181
      restartPolicy: Always
