apiVersion: v1
kind: Service
metadata:
  labels:
    name: zookeeper 
  name: zookeeper
spec:
  type: NodePort
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
    stage: dev
